import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApi }        from '../hooks/useApi'
import { reorderService } from '../services/apiServices'
import { Card, CardHeader } from '../components/ui/Card'
import { useMLStatus }   from '../hooks/useMLStatus'
import WaitingForData    from '../components/ui/WaitingForData'
import Badge          from '../components/ui/Badge'
import Button         from '../components/ui/Button'
import LoadingSpinner from '../components/ui/LoadingSpinner'

const URGENCY_MAP = {
  critical: { variant:'red',   label:'Critical' },
  high:     { variant:'amber', label:'High'     },
  medium:   { variant:'blue',  label:'Medium'   },
  low:      { variant:'teal',  label:'Low'      },
}

export default function ReorderPage() {
  const navigate = useNavigate()
  const { hasMLPredictions } = useMLStatus()
  const { data, loading, refetch } = useApi(reorderService.getSuggestions)

  const [approved,  setApproved]  = useState(new Set())
  const [dismissed, setDismissed] = useState(new Set())

  const suggestions = data?.data?.map((item, i) => ({
    id:           i,
    emoji:        item.emoji || '📦',
    name:         item.product_name || `Product ${item.item_nbr}`,
    category:     item.category || 'General',
    current:      Math.round(item.stock || 0),
    safety:       Math.round(item.safety_stock || 0),
    reorder_pt:   Math.round(item.reorder_point || 0),
    suggested_qty:Math.round(item.reorder_qty || 0),
    unit:         item.unit || 'units',
    urgency:      item.stock_status === 'Out of Stock' ? 'critical'
                : item.stock_status === 'Low Stock'    ? 'high'
                : 'medium',
    est_cost:     Math.round((item.reorder_qty || 0) * (item.unit_price || 50)),
  })) || []

  const visible = suggestions.filter(s => !dismissed.has(s.id))

  const handleApprove = async (id) => {
    try { await reorderService.approve(id) } catch {}
    setApproved(prev => new Set([...prev, id]))
  }

  const handleDismiss = async (id) => {
    try { await reorderService.dismiss(id) } catch {}
    setDismissed(prev => new Set([...prev, id]))
  }

  const totalCost = visible
    .filter(s => !approved.has(s.id))
    .reduce((sum, s) => sum + s.est_cost, 0)

  // ── Waiting state ──────────────────────────────────────
  if (!hasMLPredictions) return (
    <WaitingForData
      icon="🔁"
      title="No reorder suggestions yet"
      message="Reorder suggestions are generated by AI based on your sales patterns and predicted demand. Upload your past sales history to activate this feature."
      actionLabel="Upload Sales History →"
      actionTo="/onboarding"
      secondaryLabel="I'll record sales via POS instead"
      onSecondary={() => navigate('/pos')}
    />
  )

  return (
    <div className="space-y-5">

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display font-bold text-[1.3rem] text-[var(--ink)]">Reorder Engine</h2>
          <p className="text-[0.82rem] text-[var(--muted)] mt-0.5">
            AI-generated suggestions based on your sales patterns and predicted demand
          </p>
        </div>
        <Button variant="outline" size="md" onClick={refetch}>↻ Refresh</Button>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-4 gap-4">
        {[
          { label:'Pending',       value: visible.filter(s=>!approved.has(s.id)).length, color:'var(--teal)' },
          { label:'Critical',      value: visible.filter(s=>s.urgency==='critical').length, color:'#ef4444' },
          { label:'Approved',      value: approved.size, color:'#22c55e' },
          { label:'Est. Cost',     value:`₹${totalCost.toLocaleString('en-IN')}`, color:'#3b82f6' },
        ].map((s) => (
          <div key={s.label}
               className="bg-white border border-[var(--border)] rounded-[12px] px-5 py-4"
               style={{ boxShadow:'var(--shadow-sm)' }}>
            <p className="text-[0.7rem] font-extrabold uppercase tracking-widest text-[var(--muted)] mb-1">{s.label}</p>
            <p className="font-display font-bold text-[1.6rem] leading-none" style={{ color:s.color }}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Table */}
      <Card>
        <CardHeader
          title={`Reorder Suggestions (${visible.length})`}
          icon="🔁"
          right={
            <div className="flex gap-2">
              <Badge variant="red">{visible.filter(s=>s.urgency==='critical').length} critical</Badge>
              <Button size="sm" onClick={() => visible.forEach(s => handleApprove(s.id))}>
                Approve All
              </Button>
            </div>
          }
        />
        {loading ? <LoadingSpinner /> : (
          <table className="w-full border-collapse">
            <thead>
              <tr>
                {['Product','Current Stock','Safety Stock','Reorder Point','Suggested Qty','Est. Cost','Urgency','Action'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-[0.67rem] font-extrabold tracking-widest
                                         uppercase text-[var(--muted)] border-b border-[var(--border)] bg-[var(--cream)]">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {visible.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-5 py-12 text-center text-[var(--muted)] text-sm">
                    ✅ No pending reorder suggestions. All stock levels are healthy!
                  </td>
                </tr>
              ) : visible.map((s) => {
                const urg        = URGENCY_MAP[s.urgency] || URGENCY_MAP.low
                const isApproved = approved.has(s.id)
                return (
                  <tr key={s.id}
                      className={`border-b border-[var(--border)] last:border-0 transition-colors
                                  ${isApproved ? 'opacity-50 bg-green-50' : 'hover:bg-[var(--teal-pale)]'}`}>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <span className="text-lg">{s.emoji}</span>
                        <span className="font-semibold text-[0.85rem] text-[var(--ink)]">{s.name}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className="font-bold text-[0.85rem]"
                            style={{ color: s.current <= s.safety ? '#ef4444' : 'var(--ink)' }}>
                        {s.current} {s.unit}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-[0.85rem] text-[var(--muted)] font-medium">{s.safety} {s.unit}</td>
                    <td className="px-4 py-3 text-[0.85rem] text-[var(--muted)] font-medium">{s.reorder_pt} {s.unit}</td>
                    <td className="px-4 py-3 font-bold text-[0.85rem] text-[var(--teal)]">{s.suggested_qty} {s.unit}</td>
                    <td className="px-4 py-3 font-bold text-[0.85rem] text-[var(--ink)]">₹{s.est_cost.toLocaleString('en-IN')}</td>
                    <td className="px-4 py-3"><Badge variant={urg.variant}>{urg.label}</Badge></td>
                    <td className="px-4 py-3">
                      {isApproved ? (
                        <span className="text-[0.76rem] text-green-600 font-bold">✓ Approved</span>
                      ) : (
                        <div className="flex gap-2">
                          <button onClick={() => handleApprove(s.id)}
                                  className="text-[0.74rem] text-[var(--teal)] font-bold hover:underline bg-transparent border-0 cursor-pointer">
                            Approve
                          </button>
                          <button onClick={() => handleDismiss(s.id)}
                                  className="text-[0.74rem] text-red-400 font-semibold hover:underline bg-transparent border-0 cursor-pointer">
                            Dismiss
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </Card>
    </div>
  )
}